### ISSUE TITLE
typing.Protocol requires Python 3.8+

### ISSUE THREAD

**Issue by tekktrik** [adafruit/Adafruit_CircuitPython_Requests#106]
I haven't tested this, but since there is no alternative use of `typing_extensions.Protocol`, there many be issues where Blinka is running on 3,7 and cannot use this library, correct?

**Comment by dhalbert** [comment]
`typing_extensions` is backported to 3.7, so as long as it gets imported at some point, it should be OK?

**Comment by tekktrik** [comment]
Okay, I can work it in

**Comment by dhalbert** [comment]
that is, you could try to import `Protocol` from typing, and if it fails, import it from `typing_extensions`. But you've seen that before, I'm pretty sure.

**Comment by tekktrik** [comment]
Alright, I re-purposed #107 to solve this since it was just appeasing the formatter anyways!
