### ISSUE TITLE
Move typing annotation definitions to `circuitpython_typing`

### ISSUE THREAD

**Issue by tekktrik** [adafruit/Adafruit_CircuitPython_Requests#113]
This library may improve from having some of the type annotations reworked and checked, as well as moved to `circuitpython_typing`.  This might improve readability of the library.

**Comment by dhalbert** [comment]
I have a branch where I started to do this: https://github.com/adafruit/Adafruit_CircuitPython_Requests/compare/main...dhalbert:Adafruit_CircuitPython_Requests:change-exceptions

**Comment by justmobilize** [comment]
@dhalbert can this be closed? The typing is in `adafruit_typing` and I removed it from here, and then connection_manager once I saw it in the typing lib

**Comment by dhalbert** [comment]
Fixed by https://github.com/adafruit/Adafruit_CircuitPython_Typing/pull/35, I think.
