### ISSUE TITLE
Wrong type annotation for headers

### ISSUE THREAD

**Issue by tekktrik** [adafruit/Adafruit_CircuitPython_Requests#116]
Pretty sure `headers` is typed incorrectly as an argument in a few places - it's listed as a `List` but shouldn't be.

**Comment by gustavomfb** [comment]
can you asign me this one?

**Comment by tekktrik** [comment]
Sure thing!

**Comment by dhalbert** [comment]
> Done! how should I link my PR to this issue? I'm new in rep contributing.

To link an issue, click on "Development" in the right sidebar, or use a phrase like "Fixes #nnn". See https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by gustavomfb** [comment]
Tks!!
