### ISSUE TITLE
Adafruit_Hue-Circuitpython_Requests - File "adafruit_requests.py", line 419, in json

### ISSUE THREAD

**Issue by cn-schuh** [adafruit/Adafruit_CircuitPython_Requests#125]
Hi, i am not sure this is the correct way.

Currently i am experiencing with the adafruit_hue Circuitpython lib

I am using a Adafruit Feather RP2040 with a AirLift FeatherWing – ESP32 WiFi Co-Processor. (optianally i did a test with an EdgeBadge and and a Airlift Breakout).
I tested Circuitpython 7.3.3 and 8.0.0 - Beta 6 and the controller should be compatible, i guess.

Following this guide:
[https://learn.adafruit.com/pyportal-phi ... controller](https://learn.adafruit.com/pyportal-philips-hue-lighting-controller)
or other available guides regarding Adafruit_Hue.

My code fails always with the same error:

Traceback (most recent call last):
File "code.py", line 49, in <module>
File "/lib/adafruit_hue.py", line 109, in discover_bridge
File "/lib/adafruit_requests.py", line 419, in json
ValueError: syntax error in JSON

during executing of functions like
ip = my_bridge.discover_bridge()
or
my_bridge.get_groups()
and all other HUE functions.

The JSON file of my HUE Box is arround 30 KB. i guess it must be something related on the format. The JSON itself is valid.

To be sure the problem is not related on the Adafruit_HUE lib, I did another test, without Adafruit_HUE:

Usage of the test was the guide below:
[https://learn.adafruit.com/adafruit-air ... et-connect](https://learn.adafruit.com/adafruit-airlift-featherwing-esp32-wifi-co-processor-featherwing/internet-connect)

Result:
The first json cames from the guide above, the second and third JSON from my HUE bridge.

Fetching json from http://api.coindesk.com/v1/bpi/currentprice/USD.json

{'time': {'updated': 'Jan 11, 2023 08:28:00 UTC', 'updatedISO': '2023-01-11T08:28:00+00:00', 'updateduk': 'Jan 11, 2023 at 08:28 GMT'}, 'disclaimer': 'This data was produced from the CoinDesk BANNED Price Index (USD). Non-USD currency data converted using hourly conversion rate from openexchangerates.org', 'bpi': {'USD': {'code': 'USD', 'description': 'United States Dollar', 'rate_float': 17428.1, 'rate': '17,428.0921'}}}

Fetching json from [http://192.168.178.26/api/-lxlSLEO1If8k ... ZdrJJNdU4/](http://192.168.178.26/api/-lxlSLEO1If8kEjry2ar2jrv6c4WhZEZdrJJNdU4/)

Traceback (most recent call last):
File "code.py", line 71, in <module>
File "adafruit_requests.py", line 419, in json
ValueError: syntax error in JSON

Fetching json from [http://192.168.178.26/api/-lxlSLEO1If8k ... 4/lights/7](http://192.168.178.26/api/-lxlSLEO1If8kEjry2ar2jrv6c4WhZEZdrJJNdU4/lights/7)

Traceback (most recent call last):
File "code.py", line 71, in <module>
File "adafruit_requests.py", line 419, in json
ValueError: syntax error in JSON

Code done running.

As you can see, the error File "adafruit_requests.py", line 419, in json ValueError: syntax error in JSON is always identical.

**Comment by anecdata** [comment]
You may be experiencing #38. Can you print the headers that come back in the response to the request?

**Comment by cn-schuh** [comment]
One further info. I can fire a event once a time before the syntax error occurs.
For example: my_bridge.set_light(48, on=True) is turning light 48 on, but than code crashed.

**Comment by anecdata** [comment]
Those seem to be OK, except that there's no content-length or chunked encoding. There is an open PR #123  to handle that case.

What do you get when you `print(r.content)` instead of `print(r.json)`?

**Comment by cn-schuh** [comment]
response.json():
Traceback (most recent call last):
  File "code.py", line 54, in <module>
  File "adafruit_requests.py", line 419, in json
ValueError: syntax error in JSON

###

response.content:
b''

I guess both contents are empty

**Comment by anecdata** [comment]
You've verified that the JSON is valid, so I'd suggest downloading the code from the PR above and seeing if that helps.

**Comment by cn-schuh** [comment]
Thanks, i will run some tests with PR https://github.com/adafruit/Adafruit_CircuitPython_Requests/pull/123 and reply with an update.

**Comment by cn-schuh** [comment]
Currently the test seems to be stable. The error can be reproduced only when request.get will be executed quite often or during or the json file is huge. But this can be handled. Definetely the Timeout is an improvement.
Thanks.

**Comment by anecdata** [comment]
Closing as fixed by #123
