### ISSUE TITLE
Please re-work examples to not use deprecated `set_socket`

### ISSUE THREAD

**Issue by jepler** [adafruit/Adafruit_CircuitPython_Requests#128]

**Comment by hauserkristof** [comment]
Hey @jepler !

Can you help me please, that what is the current correct usage instead of `set_socket` ?

Thank you!

**Comment by jepler** [comment]
Roughly, instead of
```
import adafruit_requests as requests
requests.set_socket(...)
requests.get(...)
```
the new structure is
```
import adafruit_requests
requests = adafruit_requests.Session(...)
requests.get(...)
```
however, I'm not sure that this will actually work for esp32spi-based boards ("airlift"). I've asked @FoamyGuy via discord about it.

**Comment by toxicantidote** [comment]
For anyone who finds this while Googling how to use this library like I did, check out [this Adafruit tutorial](https://learn.adafruit.com/pico-w-wifi-with-circuitpython/pico-w-requests-test-adafruit-quotes) for a more specific, working example.

**Comment by justmobilize** [comment]
I am working through a refactor for requests and once that is done, will be updating and testing all the examples

**Comment by justmobilize** [comment]
All examples in https://github.com/adafruit/Adafruit_CircuitPython_Requests/pull/151 have been updated to use `adafruit_requests.Session` and `os.getenv`

**Comment by justmobilize** [comment]
@jepler https://github.com/adafruit/Adafruit_CircuitPython_Requests/pull/151 is merged. Are the changes sufficient to close this?

**Comment by anecdata** [comment]
I think jepler is out. Closing due to merge of #151.
