### ISSUE TITLE
Can't keep the session like in requests in Cpython

### ISSUE THREAD

**Issue by chechigp** [adafruit/Adafruit_CircuitPython_Requests#137]
I'm trying to login and get some data from an api, I tried with the request library in Cpython and works well. 

1. Create a session object
2. Post the login data with the session method
3. Get the api data with the session method

But when I tried with circuitpython and this library I cant get the api data (3) because it redirect me to the login page.
I think there are some redirects in the point 3 as I can see in postman

There is any limitation or feature that I'm missing?
I can share the code if it's needed.

Thanks for your time

**Comment by tannewt** [comment]
I suspect the post is setting a cookie but adafruit_requests doesn't manage cookies for you. So, it's a missing feature of normal requests.
