### ISSUE TITLE
AttributeError: 'socket' object has no attribute 'send'

### ISSUE THREAD

**Issue by robmarkcole** [adafruit/Adafruit_CircuitPython_Requests#14]
Release 20191019 with `adafruit_requests.py` copied to the Metro M4 Express AirLift (WiFi)
Using [this example](https://learn.adafruit.com/adafruit-pyportal/internet-connect#connect-to-wifi-17-4) I get the error:
```
Connecting to AP...
could not connect to AP, retrying:  ('Failed to connect to ssid', b'ColesWiFi')
Connected to ColesWiFi 	RSSI: -75
My IP address is 192.168.1.135
IP lookup adafruit.com: 104.20.39.240
Ping google.com: 10 ms
Fetching text from http://wifitest.adafruit.com/testwifi/index.html
Traceback (most recent call last):
  File "code.py", line 51, in <module>
  File "/lib/adafruit_requests.py", line 270, in get
  File "/lib/adafruit_requests.py", line 236, in request
  File "/lib/adafruit_requests.py", line 195, in request
AttributeError: 'socket' object has no attribute 'send'
```

Duplicate of https://github.com/adafruit/Adafruit_CircuitPython_Bundle/issues/203

**Comment by dansteingart** [comment]
same error. Is there anything else known before the thanksgiving yakshave begins?

**Comment by jerryneedell** [comment]
I just ran the esp32spi_simpletest on Metro  M4 Airlift. I have CP5.0-Beta installed and the latest libraries from the "bundle"  -- have you tried updating all the libraries? What version of CP are you running?

**Comment by dansteingart** [comment]
I'm running 4.1 "stable" and accompanying libraries. Will give that a shot. Thx.

**Comment by jerryneedell** [comment]
I also ran it with 4.10. Make sure you have the latest libraries.
```
Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 4.1.0 on 2019-08-02; Adafruit Metro M4 Airlift Lite with samd51j19
>>> import esp32spi_simpletest
ESP32 SPI webclient test
ESP32 found and in idle mode
Firmware vers. bytearray(b'1.3.1\x00')
MAC addr: ['0xdd', '0xa9', '0xe', '0x33', '0x4f', '0xc4']
        Needell Airport         RSSI: -54
        Needell Airport         RSSI: -70
        Needell Airport         RSSI: -76
        Needell Airport         RSSI: -83
        xfinitywifi             RSSI: -87
Connecting to AP...
Connected to Needell Airport    RSSI: -51
My IP address is 10.0.0.64
IP lookup adafruit.com: 104.20.39.240
Ping google.com: 60 ms
Fetching text from http://wifitest.adafruit.com/testwifi/index.html
----------------------------------------
This is a test of Adafruit WiFi!
If you can read this, its working :)

----------------------------------------

Fetching json from http://api.coindesk.com/v1/bpi/currentprice/USD.json
----------------------------------------
{'time': {'updated': 'Nov 29, 2019 03:37:00 UTC', 'updatedISO': '2019-11-29T03:37:00+00:00', 'updateduk': 'Nov 29, 2019 at 03:37 GMT'}, 'disclaimer': 'This data was produced from the CoinDesk Bitcoin Price Index (USD). Non-USD currency data converted using hourly conversion rate from openexchangerates.org', 'bpi': {'USD': {'code': 'USD', 'description': 'United States Dollar', 'rate_float': 7514.63, 'rate': '7,514.6283'}}}
----------------------------------------
Done!
>>> 
```

**Comment by robmarkcole** [comment]
Problem persists on `5.0.0-beta.0 `

**Comment by jerryneedell** [comment]
Have you updated the libraries ?

**Comment by robmarkcole** [comment]
HI @jerryneedell 
I've updated the bundle to `20191019` tag and the issue is now resolved. Many thanks!

However I do get a variety of error codes relating to dropped connection or incomplete data unless the devices is very close to the router, is this normal?

**Comment by brentru** [comment]
@robmarkcole  
> However I do get a variety of error codes relating to dropped connection or incomplete data unless the devices is very close to the router, is this normal?

I haven't experienced this with a Metro M4 AirLift before. Do you have any examples of these error codes? If so, could you open a new issue and tag me. I'll check it out. Thanks!
