### ISSUE TITLE
gaierror, Out of sockets, Sending Request Failure: due to syntax

### ISSUE THREAD

**Issue by DJDevon3** [adafruit/Adafruit_CircuitPython_Requests#145]
Circuit Python 8.2.7, Adafruit Feather ESP32-S3
I've tracked down a weird syntax issue that caused me a lot of headache.

```py
response = requests.get(DATA_SOURCE).json()

response = requests.get(DATA_SOURCE).close() # valid syntax, doesn't do anything, but will leak sockets.
response.close() # flat out does not work with .json above
```
I believe I got that syntax from Neradoc or Deshipu a long time ago and I've been using it ever since in my personal projects.  It only reduces the code by 1 line but it worked... until 8.2.7 where it exposed a potential bug when my script starting failing in unexpected ways completely deviating from its past stable behavior.

As RimWolf & Anecdata have pointed out the correct way is
```py
response = requests.get(DATA_SOURCE)
owm_response = response.json()
do_something_with(owm_response)
response.close()
```
Above method "should" automatically close the response and seems to work ok.
or 

```py
with requests.get(DATA_SOURCE) as response:
    owm_response = response.json()
    do_something_with(owm_response)
```
Above method `with requests` will close a socket automatically so response.close() is unneeded but you can still use it explicitly if you want.

The problem that cropped up is if you use `response = requests.get(DATA_SOURCE).json()` it will slowly leak sockets failing to close them.  It will work fine for hours and even days at a time but will eventually fail to close a socket properly which will end up with a -2 gaierror and/or 
```py
Traceback (most recent call last):
  File "adafruit_requests.py", line 500, in _get_socket
RuntimeError: Out of sockets
```
The culprit is 
`response = requests.get(DATA_SOURCE).json()` is valid syntax and does not cause an error but will 100% eventually fail.  I've gone as long as 4 days without encountering that error but it will happen eventually.  This syntax seems to work on the surface at first but also makes using response.close() impossible due to a dict error.

This issue is related to OSError -2 gaierror and RuntimeError: Out of sockets.

I modified my requests script to use the default way as Rimwolf & Anecdata advised and have not had a gaierror, sending request error, or socket error since.  The biggest problem with tracking this one down is how randomly intermittent it is.  It could take days or weeks depending on your polling rate.  My polling rate is typically 15 minutes. 

I think this is a syntax issue as requests wants things in a specific way.  If you deviate from the norm it will not complain about the syntax and instead will start throwing random errors.  There are a lot of response.close() open issues and I'm not sure where this one fits. Just wanted to share my experience fighting against it for weeks trying to track down the gaierror which eventually led to this.

**Comment by DJDevon3** [comment]
I've changed syntax to `with requests.get(DATA_SOURCE) as owm_request` and still getting some kind of socket leak. Here's my serial output.  After 3 days it errored with an AdafruitIO error.  Currently if that error is detected it does a supervisor.reload which frees everything up again and will work for a couple hours or days but will eventually error again.  

```py
===============================
Board Uptime:  3.2 days
Temp:  81.8681
Actual Temp: 81.1
| Connecting to WiFi...
| ✅ WiFi!
| | Attempting to GET Weather!
| | Account within Request Limit
| | ✅ Connected to OpenWeatherMap
| | | Sunrise: 06:50
| | | Sunset: 17:27
| | | Temp: 84.61
| | | Pressure: 1011
| | | Humidity: 68
| | | Weather Type: Clear
| | | Wind Speed: 10.36
| | | Timestamp: 2023/11/26 15:05
| | ✂️ Disconnected from OpenWeatherMap
| | ❌ AdafruitIO_MQTTError: 
 MQTT Error: Unable to connect to Adafruit IO.
Code done running.
soft reboot
``` 
[Full code for Feather Weather here](https://github.com/DJDevon3/My_Circuit_Python_Projects/blob/main/Boards/espressif/Adafruit%20Feather%20ESP32-S3/3.5%20TFT%20Featherwing/Feather%20Weather%20MQTT/code.py)

**Comment by anecdata** [comment]
Can you post the full stack trace.. it seems to be coming from adafruit_minimqtt or adafruit_io?

**Comment by DJDevon3** [comment]
Because I'm using exception handlers now there is no traceback, only the error message. I tried finding where that error message is coming from but I can't even find that line in mmqtt or adafruit_io library.  `MQTT Error: Unable to connect to Adafruit IO.` I have no idea where that is coming from.

I have it failing reliably, as in it will happen once or twice per 24 hours then automatically reload. I can't speed up the process or I'll get temp banned by OpenWeatherMap. I have to let it ride waiting every 15 minutes.  If I remove the part for OpenWeatherMap, that would change the amount of sockets it would normally have.  

It's in a state that is usable only because of supervisor.reload().  If I remove that, the script will fail to connect infinitely when that error eventually occurs. It only has to show up once and from then on any attempts to connect to adafruitio fail.  I'm not getting any errors in adafruitio dashboard live errors.  From AdafruitIO's perspective there is no connection taking place to create an error on their side. It feels like I'm running out of sockets still but the error doesn't say that.

If you have any tips on how to better track something like this down I'm all ears. Remove the exception handlers to force a traceback?

**Comment by anecdata** [comment]
You can print the traceback within the exception handler like:
```py
import traceback
# ...
try:
    # ...
except Exception as ex:  # or tuple of specific exception types)
    traceback.print_exception(ex, ex, ex.__traceback__)
```

**Comment by DJDevon3** [comment]
This was not as revealing as I'd hoped.

```py
Traceback (most recent call last):
  File "code.py", line 556, in <module>
  File "adafruit_io/adafruit_io.py", line 116, in connect
AdafruitIO_MQTTError: MQTT Error: Unable to connect to Adafruit IO.
``` 
[Line 116 in adafruit_io/adafruit_io.py](https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO/blob/eec28fef92a0a5b1e507e48c5168af822b15d6a0/adafruit_io/adafruit_io.py#L116)

**Comment by DJDevon3** [comment]
Have an idea.  Trying reconnect with a continue instead of a pass or break now.
```py
        except (AdafruitIO_MQTTError) as ex:
            print("| | ❌ AdafruitIO_MQTTError: \n", ex)
            traceback.print_exception(ex, ex, ex.__traceback__)
            io.reconnect()
            continue
```

**Comment by DJDevon3** [comment]
Here's a look at my adafruitIO live feed.

![Capture](https://github.com/adafruit/Adafruit_CircuitPython_Requests/assets/49322231/6210b1c4-927b-4c40-b236-725c99631559)

When it fails there are no errors on AdafruitIO's side. Everything looks normal from their perspective. There is no connection on their side which does correlate with a failure to send or failure to connect type of issue.  I see nothing abnormal from the AdafruitIO dashboard side.

**Comment by DJDevon3** [comment]
```py
Traceback (most recent call last):
  File "code.py", line 586, in <module>
  File "adafruit_io/adafruit_io.py", line 107, in reconnect
AdafruitIO_MQTTError: MQTT Error: Unable to reconnect to Adafruit IO.
``` 
was worth a shot.  something is very wrong if I have to go to these lengths.

**Comment by DJDevon3** [comment]
Tried to remove adafruit_io library from the equation and use only adafruit_minimqtt with the same result.

```py
===============================
Board Uptime:  2 hours
Temp:  76.1119
Actual Temp: 74.7
| Connecting to WiFi...
| ✅ WiFi!
| | Attempting to GET Weather!
| | Account within Request Limit
| | ✅ Connected to OpenWeatherMap
| | | Sunrise: 06:51
| | | Sunset: 17:26
| | | Temp: 68.22
| | | Pressure: 1017
| | | Humidity: 74
| | | Weather Type: Clear
| | | Wind Speed: 8.05
| | | Timestamp: 2023/11/27 17:46
| | ✂️ Disconnected from OpenWeatherMap
| | ✅ Connected to MQTT Broker!
| | | Published DJDevon3/feeds/BME280-Unbiased None
| | | Published DJDevon3/feeds/BME280-RealTemp None
| | | Published DJDevon3/feeds/BME280-Pressure None
| | | Published DJDevon3/feeds/BME280-Humidity None
| | | Published DJDevon3/feeds/BME280-Altitude None
| | ✂️ Disconnected from MQTT Broker
| ✂️ Disconnected from Wifi
Next Update:  15 minutes
===============================
Board Uptime:  2 hours
Temp:  75.9843
Actual Temp: 74.6
| Connecting to WiFi...
| ✅ WiFi!
| | Attempting to GET Weather!
| | Account within Request Limit
| | ✅ Connected to OpenWeatherMap
| | | Sunrise: 06:51
| | | Sunset: 17:26
| | | Temp: 66.11
| | | Pressure: 1017
| | | Humidity: 78
| | | Weather Type: Clear
| | | Wind Speed: 5.01
| | | Timestamp: 2023/11/27 18:02
| | ✂️ Disconnected from OpenWeatherMap
| | ❌ Failed to connect, retrying
 Out of sockets
| | Attempting to GET Weather!
| | Account within Request Limit
| | ✅ Connected to OpenWeatherMap
| | | Sunrise: 06:51
| | | Sunset: 17:26
| | | Temp: 65.77
| | | Pressure: 1016
| | | Humidity: 79
| | | Weather Type: Clear
| | | Wind Speed: 5.01
| | | Timestamp: 2023/11/27 18:06
| | ✂️ Disconnected from OpenWeatherMap
| | ❌ Failed to connect, retrying
 Out of sockets
| | Attempting to GET Weather!
| | Account within Request Limit
| | ✅ Connected to OpenWeatherMap
| | | Sunrise: 06:51
| | | Sunset: 17:26
| | | Temp: 65.77
| | | Pressure: 1016
| | | Humidity: 79
| | | Weather Type: Clear
| | | Wind Speed: 3.0
| | | Timestamp: 2023/11/27 18:10
| | ✂️ Disconnected from OpenWeatherMap
| | ❌ Failed to connect, retrying
 Out of sockets
```

Once it fails it will not reconnect without a soft reboot via supervisor.reload or a hard reset.

**Comment by DJDevon3** [comment]
I have a theory that it's looping connect_retries amount of times each connection, successfully, and then fails. Some kind of misplaced loop counter issue? Or it's not resetting connect_retries back to 0 if there was a successful connection made so it's 5 retries per lifecycle of the script and then it permanently fails.

```py
socket_timeout: int = 1,
connect_retries: int = 5,
```

**Comment by DJDevon3** [comment]
Anecdata & Justin have been a tremendous help in Discord going over different iterations to force failures.  Think we're getting close.  It's definitely some type of failure to close sockets properly issue.  The library should be closing the sockets and it's not happening.  Upon bisecting more figured out that adafruit_minimqtt will correctly run infinitely.  OpenWeatherMap only using adafruit_requests will eventually fail with an out of sockets error.  This one has taken a long road to circle back and is looking like a requests related failure to close socket issue after all.

**Comment by DJDevon3** [comment]
Ran it overnight with great success by adding:
```py
owm_request.close()
requests._free_sockets()
pass
```
to manually close sockets correctly.  why this works I don't know. Anecdata would have to chime in as that's deeper than I go.

requests._default_session._free_sockets() did not work and threw errors.  Can consider this a potential temporary work around if anyone is encountering an Out of Sockets issue with 8.2.x  I think we were able to narrow it down with enough context to give someone a good shot at fixing this.

**Comment by DJDevon3** [comment]
Moved
```py
requests = adafruit_requests.Session(pool, ssl.create_default_context())
``` 
to outside the main loop and removed
```py
owm_request.close()
requests._free_sockets()
```
and it works as intended. I must have moved it inside the loop at some point in time and that's what broke everything.  Hard lesson learned.  Always keep adafruit_requests.Session() outside of the main loop just like socketpool.

This one is indeed a user and syntax error.

**Comment by DJDevon3** [comment]
Been running for half a day with over 30 attempts without a single failure.  Closing.
