### ISSUE TITLE
Issue with sending header values twice

### ISSUE THREAD

**Issue by justmobilize** [adafruit/Adafruit_CircuitPython_Requests#148]
When helping a member in the discord channel `#help-with-circuitpython`, I had made the mistake of thinking that this library didn't automatically deal with turning a `dict` into a `urlencoded` string. I had them convert it by hand and try and it worked.

As it turns out - it does, but also sends the header `Content-Type: application/x-www-form-urlencoded`, which some systems (`Spotify` as one) can't handle getting the header twice.

I would like to open a PR to check the header for an existing `Content-Type` before adding it's own (both for `urlencoded` and `json`). It would implement a method to check for an existing value since we would also want to check for casing mis-matches.

**Comment by brentru** [comment]
@justmobilize  I am re-opening this issue as https://github.com/adafruit/Adafruit_CircuitPython_Requests/pull/149 is causing a "TypeError: wrong number of arguments" error as seen here: https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO/issues/115. I am also able to locally reproduce this.


The issue appears to be with doing a GET with only headers like in `adafruit_io.py`'s `get` function:

```
    def _get(self, path: str):
        """
        GET data from Adafruit IO

        :param str path: Formatted Adafruit IO URL from _compose_path
        """
        with self._http.get(
            path, headers=self._create_headers(self._aio_headers[1])
        ) as response:
            self._handle_error(response)
            json_data = response.json()
        return json_data
```

Tracing through this, your new `send_header` expects (`self, socket, header, value)`. However, in this case, the header is the `X-AIO-KEY` and the `value` is of `None` type.


On L561, in `send_header`, the `value` is sent via `_send_as_bytes` but it is a `None`Type where `send_as_bytes` expects a `String`:
`self._send_as_bytes(socket, value)`

@justmobilize  Would you be able to resolve this? Do you want me to resolve this?

**Comment by justmobilize** [comment]
@brentru I'm happy to take a look at this

**Comment by justmobilize** [comment]
@brentru looking, my PR just changed from `.encode` to `bytes`

Old:
<img width="335" alt="image" src="https://github.com/adafruit/Adafruit_CircuitPython_Requests/assets/1547881/149d7a40-6713-4088-9a57-bc075d8bf7e6">

Looking at `CPython` requests:
<img width="1007" alt="image" src="https://github.com/adafruit/Adafruit_CircuitPython_Requests/assets/1547881/338679b9-e4be-4552-adf1-cb0a226a2dfd">
 
If it's `None` it just doesn't send it, and if it's not a `str` it raises.

Looking into their code they:

1. [Remove `Nones`](https://github.com/psf/requests/blob/96b22fa18c00831656ee4b286bf1c9062459b00a/src/requests/models.py#L386)
2. [Error on non `str|bytes`](https://github.com/psf/requests/blob/96b22fa18c00831656ee4b286bf1c9062459b00a/src/requests/utils.py#L1040)

I'll get a PR opened with tests in the next day or so.

I might recommend `Adafruit_CircuitPython_AdafruitIO` also add an exception here to let the user know the data is missing (otherwise I assume they would just get an auth error after the fact).

**Comment by justmobilize** [comment]
Code change here: https://github.com/adafruit/Adafruit_CircuitPython_Requests/pull/152. Want to make sure the method makes sense, then will add tests

**Comment by justmobilize** [comment]
@brentru just waiting on an initial code review

**Comment by justmobilize** [comment]
@brentru my code fix is merged. Can you confirm it fixes the issue and close this?

**Comment by justmobilize** [comment]
Scratch that. I see the user already tested. Closing.
