### ISSUE TITLE
TypeError: wrong number of arguments when posting bytes array

### ISSUE THREAD

**Issue by jimbobbennett** [adafruit/Adafruit_CircuitPython_Requests#20]
I have a `bytearray` containing image data from the [TTL camera sample](https://github.com/adafruit/Adafruit_CircuitPython_VC0706/blob/master/examples/vc0706_snapshot_filesystem.py). I want to POST this as an octet stream to a REST endpoint.

My code:

```python
import adafruit_requests as requests

...

buffer = bytearray()

headers={
            'Content-Type': 'application/octet-stream',
            'Prediction-Key': prediction_key
        }

r = requests.request('POST', prediction_endpoint, data=buffer, headers=headers)
```

When I run this I get the following:

```sh
......Traceback (most recent call last):
  File "code.py", line 85, in <module>
  File "adafruit_requests.py", line 242, in request
  File "adafruit_requests.py", line 224, in request
TypeError: wrong number of arguments
```

Running the code locally I've tracked down the error to this line:

```python
if data:
   sock.send(bytes(data, "utf-8"))
```

If I change the call to `bytes()` to remove the encoding parameter, it works.

```python
if data:
   sock.send(bytes(data))
```

Does the CircuitPython implementation of `bytes` have an encoding parameter?

**Comment by jimbobbennett** [comment]
PR #21 raised to remove this parameter, if this is the correct fix

**Comment by FoamyGuy** [comment]
Odd, I am able to run this at REPL and don't get the same error.
```
>>> bytes("hello", "utf-8")
b'hello'
```

**Comment by jimbobbennett** [comment]
@FoamyGuy - I think it is because it is a `bytesarray`.

Just tested in the REPL:

```python
>>> b = bytearray(10)
>>> bytes(b, 'utf-8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: wrong number of arguments 
```

**Comment by FoamyGuy** [comment]
Looks like possible the issue is more related to the bytearray than the encoding param I use a bytebuffer instead of a string it reports the error:
```
>>> buffer = bytearray()
>>> bytes(buffer, "utf-8")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: wrong number of arguments
```

**Comment by FoamyGuy** [comment]
This does not appear to be possible in CPython 3.7 either though the error is different than CircuitPython: 
```
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> buffer = bytearray()
>>> bytes(buffer, "utf-8")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: encoding without a string argument
```

**Comment by jimbobbennett** [comment]
I've changed my PR to check the type, and not pass the encoding for `bytearray`, but keep it for other types.
