### ISSUE TITLE
Requests with CPython Native Socket

### ISSUE THREAD

**Issue by brentru** [adafruit/Adafruit_CircuitPython_Requests#28]
The CircuitPython_Requests module is currently untested with [CPython's socket low-level interface](https://docs.python.org/3/library/socket.html). 

A new requests_simpletest example would need to be added, too.
* https://github.com/adafruit/Adafruit_CircuitPython_Requests/blob/master/examples/requests_simpletest.py

After updating for the CPython native socket, we may need to update ESP32, Ethernet and Cellular socket-like implementations for compatibility.

**Comment by tannewt** [comment]
Furthermore, it should always use the `recv*_into` forms for receive to minimize memory allocations. (The others create new byte arrays to return.)

**Comment by tannewt** [comment]
I'm working on this.
