### ISSUE TITLE
Requests in CircuitPython Library Bundle 5.x-mpy-20200918 seems incompatible with CircuitPython 5.3.1

### ISSUE THREAD

**Issue by anecdata** [adafruit/Adafruit_CircuitPython_Requests#32]
Requests work here:
Adafruit Feather M4 Express with samd51j19
CircuitPython 5.3.1 on 2020-07-13
CircuitPython Library Bundle 5.x-mpy-20200917

But not here:
Adafruit Feather M4 Express with samd51j19
CircuitPython 5.3.1 on 2020-07-13
CircuitPython Library Bundle 5.x-mpy-20200918

```
Socket missing recv_into. Using more memory to be compatible
Traceback (most recent call last):
  File "code.py", line 1446, in <module>
  File "code.py", line 527, in http_get
  File "code.py", line 521, in http_get
  File "adafruit_requests.py", line 583, in get
  File "adafruit_requests.py", line 494, in request
  File "adafruit_requests.py", line 100, in __init__
  File "adafruit_requests.py", line 128, in _readto
AttributeError: 'bytearray' object has no attribute 'find'
```

Seems to be this 6.0.0-alpha change:
`Add .find, .rfind, .index and .rindex to bytearray for CPython-compatible builds.`

Is this a case where the 5.x and 6.x bundles should diverge, should devices running 5.3.1 max out with the 20200917 bundle, or is it worth making the library backwards-compatible?

The offending line 521 is:
`response = requests.get(url, data=None, json=None, headers=custom_hdrs, stream=False, timeout=timeout)`

**Comment by tannewt** [comment]
Well bummer! I thought I had checked it all. *BUT* I hadn't tried 5.3.1. I'll look at hacking this to work.

**Comment by anecdata** [comment]
Sorry, I meant to test it sooner but didn't get to it.

I'll wait for the beta to drill down on this next one (if it's still happening), but new Requests may be doing something funny with ESP32SPI in alpha-3. Every other GET in my code fails quickly (tens of milliseconds) with `Failed to send 281 bytes (sent 0)`, then after about two hours , all subsequent requests get `No sockets available`.  Reverting Requests to yesterday's version works as it always has. Just thought I'd mention it in case you see something when you're looking at the code.

**Comment by tannewt** [comment]
@anecdata that sounds like a separate issue. I don't think I handle connections timing out well so that's likely the issue.

**Comment by axelmagnus** [comment]
Work around from discord:
 everything 6.0.0 (beta) but revert to 1.6.0?
https://github.com/adafruit/Adafruit_CircuitPython_Requests/releases/tag/1.6.0 (would be from adafruit-circuitpython-bundle-6.x-mpy-20200917) .
