### ISSUE TITLE
Add Parse_Headers Method

### ISSUE THREAD

**Issue by brentru** [adafruit/Adafruit_CircuitPython_Requests#4]
Add method for parsing the header portion of an HTTP request/response from the socket.

Previous implementation in ESP32SPI_Requests module:
https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI/blob/c15e8fd9c0e53bb7e0ee2f1dd105cc09a7e70b7d/adafruit_esp32spi/adafruit_esp32spi_requests.py#L223

Affects ESP32SPI WSGI Server: https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI/issues/62

**Comment by siddacious** [comment]
fixed via PR #5
