### ISSUE TITLE
Breaking change in 1.7.0: Header keys are now capitalized

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Adafruit_CircuitPython_Requests#40]
I noticed between 1.6.0 and 1.7.0, headers such as headers['content-length'] are not headers['Content-Length'], so anything that uses the head keys will need to be updated.

This issue is more of a breaking change alert due to the removal of this line:
```
title = str(title.lower(), "utf-8")
```
in https://github.com/adafruit/Adafruit_CircuitPython_Requests/pull/31/

I'm not sure if we want to put it back or just slowly change everything that broke.

**Comment by tannewt** [comment]
Looks like regular requests is case-insensitive: https://requests.readthedocs.io/en/master/user/quickstart/#response-headers

Maybe we need a wrapper object to do it that way. I removed the title.lower() because it allocates a second copy of the string when one already exists.

**Comment by makermelissa** [comment]
We could have added .lower() onto the title as it is put into the dict. To handle the differences in the PyPortal, I submitted a PR that creates a new dict and just copies the headers with lower case. This way both older and newer versions of this library should work with it.

**Comment by makermelissa** [comment]
By wrapper object, are you suggesting adding a function like get_header() that would accept lowercase and uppercase or maybe a property that lowercases it on the fly or something else?

**Comment by dhalbert** [comment]
Regular `requests` has a `CaseInsensitiveDict` class for exactly this reason:
https://github.com/psf/requests/blob/3bb13f8fbb9d4ed1a20bd33495cdc087eb062ca0/requests/structures.py#L37

**Comment by tannewt** [comment]
> We could have added .lower() onto the title as it is put into the dict. To handle the differences in the PyPortal, I submitted a PR that creates a new dict and just copies the headers with lower case. This way both older and newer versions of this library should work with it.

Calling `.lower()` is copying the string. I'm really trying to avoid that.

> By wrapper object, are you suggesting adding a function like get_header() that would accept lowercase and uppercase or maybe a property that lowercases it on the fly or something else?

No, I'm thinking along the lines of what Dan pointed out. Create an object that acts like a dictionary and does a case insensitive search on each access. That way you only pay the cost on the headers you care about.

**Comment by makermelissa** [comment]
Ok cool. Thanks. I just wanted to make sure I understood.

**Comment by justmobilize** [comment]
Is this still valid? Some header fixes were recently merged in, and if this still exists, I'm happy to work on it.

**Comment by justmobilize** [comment]
@makermelissa and @tannewt with some other bugs, I cleaned up how headers are handled. Is there any more work there I can do?

**Comment by tannewt** [comment]
I have no idea. I think you know better than I do.

**Comment by justmobilize** [comment]
I feel this is good to close
