### ISSUE TITLE
`request` should be refactored to use `parse_headers`

### ISSUE THREAD

**Issue by siddacious** [adafruit/Adafruit_CircuitPython_Requests#6]
When this lib was split out from `Adafruit_CircuitPython_ESP32SPI` `parse_headers` was inlined into the `request` method. Since it was added back for external use, it should be used here as well.

**Comment by siddacious** [comment]
(sorry @brentru I should have mentioned this in the review for `parse_headers`. I can take care of this later)

**Comment by brentru** [comment]
@siddacious 
Could you link a previous version of how it was inlined into the `request` method? Seems its a standalone method, this is the last commit of it before it was removed:
https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI/blob/8dbeef02125e4f27d49fe468d78912afc366a200/adafruit_esp32spi/adafruit_esp32spi_requests.py 

Do you think it's useful externally too, or only within `request`?

**Comment by siddacious** [comment]
Here is the section in question:
https://github.com/adafruit/Adafruit_CircuitPython_Requests/blob/f77d71377125a023d5cecdc72d541cd8ba97b104/adafruit_requests.py#L227

It's used externally in the wsgi server code in the Esp32 lib so yes it's useful externally? They're using them for different sides of the server/client divide (parsing headers for an incoming request vs. parsing the response to an outgoing request) but there is some obvious overlap there.

**Comment by brentru** [comment]
Merged into master and released, closing...
