### ISSUE TITLE
Setting up requests repeatedly (3 times) results in runtime error

### ISSUE THREAD

**Issue by askpatrickw** [adafruit/Adafruit_CircuitPython_Requests#62]
Originally I ran into this  using AIO time service, but I can reproduce just using requests.

**Simplified Test**

```python
wifi.radio.connect(config.SSID, config.WIFI_PASSWORD)
POOL = socketpool.SocketPool(wifi.radio)

while True:
    REQUESTS = adafruit_requests.Session(POOL, ssl.create_default_context())
    response = REQUESTS.get("http://wifitest.adafruit.com/testwifi/index.html")
    sleep(SLEEP_TIME)
```

Always on the 3rd attempt I get this error:

```
Traceback (most recent call last):
  File "code.py", line 23, in <module>
  File "adafruit_requests.py", line 595, in get
  File "adafruit_requests.py", line 559, in request
  File "adafruit_requests.py", line 428, in _get_socket
RuntimeError: Sending request failed
```

**Workaround**
Setup requests before the while loop.

**Comment by Dcai169** [comment]
I am also having this issue. I can't send more than two requests without an error.

**Comment by anecdata** [comment]
`REQUESTS = adafruit_requests.Session(POOL, ssl.create_default_context())` only needs to be done once, rather than in the loop. ESP32-S2 is currently limited to 4 simultaneous sockets, HTTPS/TLS uses two per transaction.

**Comment by Dcai169** [comment]
> ESP32-S2 is currently limited to 4 simultaneous sockets, HTTPS/TLS uses two per transaction.

I assume that sockets are automatically freed when the transaction is finished?

**Comment by anecdata** [comment]
Certainly if you `close` the response or use a context manager. There's also an optimization to use the same socket (if it still exists) when you re-connect to the same protocol/address/port within a `Session`. I haven't looked at the library to see what happens when you create more than one `Session`.

**Comment by wavesailor** [comment]
I came across this problem too on my MagTag.
I was not using sockets but doing multiple requests. Some of my requests were "automatic" (to Adafruit IO)  and some I initiated to OpenWeather API.
I would get the error below:

`Traceback (most recent call last):
  File "code.py", line 23, in <module>
  File "adafruit_requests.py", line 595, in get
  File "adafruit_requests.py", line 559, in request
  File "adafruit_requests.py", line 428, in _get_socket
RuntimeError: Sending request failed
`

What seems to be the problem for me is the mixture of auto-connecting to wifi and the automatic requests to AIO for time and my own requests. What I did to get around the problem was make the connection to wifi manually and to put each of my requests and the automatic ones in their own function. But it still would be nice to figure what the error is  - could this error not perhaps include more info about what is wrong as it is very difficult to track down?

**Comment by askpatrickw** [comment]
As I re-read all this slowly and with 11 month older brain, I believe the common issue is where in the code you are creating the Radio and the Requests objects and if you're doing so in such a manner they are called more than once thus using up the sockets as Anecdata mentions here: https://github.com/adafruit/Adafruit_CircuitPython_Requests/issues/62#issuecomment-865173242

I'm going to refactor all my reusable code (initialize the network, setup the system time, etc..) so you have to pass them a Radio and\or a Requests object from the main code.py and not also inside a While loop.

If when I've done that, if I can't reproduce this I'll close it.

**Comment by askpatrickw** [comment]
If you want to play along ... 

```python
import alarm
import socketpool
import ssl
import time
import wifi

import adafruit_requests

print(f"Wake Reason: {alarm.wake_alarm}")

# Get secrets
try:
    from secrets import secrets
except ImportError:
    print("Secrets are kept in secrets.py, please add them there!")
    raise

# Setup Requests
radio = wifi.radio
pool = socketpool.SocketPool(radio)
requests = adafruit_requests.Session(pool, ssl.create_default_context())

radio.connect(secrets['ssid'], secrets['wifi_password'])

print("Request 1")
response = requests.get("https://httpbin.org/get")
print(response.status_code, response.reason)

print("Request 2")
response = requests.get("https://requestbin.net/r/5h8k316q")
print(response.status_code, response.reason)

print("Request 3")
response = requests.get("https://io.adafruit.com/api/v2/time/seconds")
print(response.status_code, response.reason)

# Create a an alarm that will trigger requested number of seconds from now.
time_alarm = alarm.time.TimeAlarm(monotonic_time=time.monotonic() + 300)
# Exit and deep sleep until the alarm wakes us.
alarm.exit_and_deep_sleep_until_alarms(time_alarm)

```

It is definitely not working reliably.

```
[tio 12:18:07] Connected

Code stopped by auto-reload.
soft reboot

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Wake Reason: None
Request 1
200 bytearray(b'OK')
Request 2
200 bytearray(b'OK')
Request 3
200 bytearray(b'OK')

Code done running.

Press any key to enter the REPL. Use CTRL-D to reload.
Pretending to deep sleep until alarm, CTRL-C or file write.
Woken up by alarm.
soft reboot

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Wake Reason: <TimeAlarm>
Request 1
Traceback (most recent call last):
  File "code.py", line 26, in <module>
  File "adafruit_requests.py", line 613, in get
  File "adafruit_requests.py", line 578, in request
OutOfRetries: Repeated socket failures

Code done running.

Press any key to enter the REPL. Use CTRL-D to reload.
```

**Comment by anecdata** [comment]
I do often get `OutOfRetries: Repeated socket failures` after `wifi` is freshly enabled, but retrying almost always works. There are some quirks in how Requests interacts with ESP32-S2.

**Comment by askpatrickw** [comment]
I added a bunch of print statements and I see this pattern (which I don't understand). 

When it works, before the `sock.connect((connect_host, port))`, self._socket_free has an object `'_socket_free': {<SSLSocket>: True}` and when it fails it does not. But it never gets to more than the 2nd retry.


```
[tio 13:35:11] Connected

# This one works ... 

946684814 Request 1
entering requests
entering _get_socket
{'_last_response': None, '_socket_free': {}, '_open_sockets': {}, '_socket_pool': <SocketPool>, '_ssl_context': <SSLContext>}
retry_count: 1
trying to create sock
create https sock
try to connect with sock: io.adafruit.com:443
{'_last_response': None, '_socket_free': {}, '_open_sockets': {}, '_socket_pool': <SocketPool>, '_ssl_context': <SSLContext>}
<SSLSocket>
entering _send_request
entering _send
entering _send
entering _send
entering _send
entering _send
entering _send
entering _send
entering _send
entering _send
entering _free_socket
System Time: struct_time(tm_year=2021, tm_mon=11, tm_mday=25, tm_hour=21, tm_min=35, tm_sec=21, tm_wday=3, tm_yday=329, tm_isdst=-1)

# This one fails 

1637876125 Request 2
entering requests
entering _get_socket
{'_last_response': None, '_socket_free': {<SSLSocket>: True}, '_open_sockets': {('io.adafruit.com', 443, 'https:'): <SSLSocket>}, '_socket_pool': <SocketPool>, '_ssl_context': <SSLContext>}
retry_count: 1
trying to create sock
create https sock
try to connect with sock: httpbin.org:443
{'_last_response': None, '_socket_free': {<SSLSocket>: True}, '_open_sockets': {('io.adafruit.com', 443, 'https:'): <SSLSocket>}, '_socket_pool': <SocketPool>, '_ssl_context': <SSLContext>}
<SSLSocket>
call free socket
entering _free_sockets
entering _close_socket
retry_count: 2
trying to create sock
create https sock
try to connect with sock: httpbin.org:443
{'_last_response': None, '_socket_free': {}, '_open_sockets': {}, '_socket_pool': <SocketPool>, '_ssl_context': <SSLContext>}
<SSLSocket>
no _socket_free.items()
{'_last_response': None, '_socket_free': {}, '_open_sockets': {}, '_socket_pool': <SocketPool>, '_ssl_context': <SSLContext>}
Traceback (most recent call last):
  File "code.py", line 37, in <module>
  File "/lib/adafruit_requests.py", line 610, in get
  File "/lib/adafruit_requests.py", line 551, in request
  File "/lib/adafruit_requests.py", line 416, in _get_socket
RuntimeError: Sending request failed

```

**Comment by askpatrickw** [comment]
I added a bunch of print statements and I see this pattern (which I don't understand).

When it works, before the `sock.connect((connect_host, port))`, self._socket_free is empty `'_socket_free': {}` and when it fails it has `'_socket_free': {<SSLSocket>: True}` when entering _get_socket.

Also, it never gets to more than the 2nd retry.

Is it reusing one socket for a different site?

```
[tio 13:49:13] Connected

# This one Fails. Notice _socket_fee is empty as it enters _get_socket

946684815 Request 1
entering requests
entering _get_socket
_get_socket Session: {'_last_response': None, '_socket_free': {}, '_open_sockets': {}, '_socket_pool': <SocketPool>, '_ssl_context': <SSLContext>}
retry_count: 1
trying to create sock
create https sock
try to connect with sock: io.adafruit.com:443
	_get_socket Session: {'_last_response': None, '_socket_free': {}, '_open_sockets': {}, '_socket_pool': <SocketPool>, '_ssl_context': <SSLContext>}
<SSLSocket>
entering _send_request
entering _send
entering _send
entering _send
entering _send
entering _send
entering _send
entering _send
entering _send
entering _send
entering _free_socket
System Time: struct_time(tm_year=2021, tm_mon=11, tm_mday=25, tm_hour=21, tm_min=49, tm_sec=24, tm_wday=3, tm_yday=329, tm_isdst=-1)

# This one Fails. Notice _socket_fee is not empty as it enters _get_socket

1637876968 Request 2
entering requests
entering _get_socket
_get_socket Session: {'_last_response': None, '_socket_free': {<SSLSocket>: True}, '_open_sockets': {('io.adafruit.com', 443, 'https:'): <SSLSocket>}, '_socket_pool': <SocketPool>, '_ssl_context': <SSLContext>}
retry_count: 1
trying to create sock
create https sock
try to connect with sock: httpbin.org:443
	_get_socket Session: {'_last_response': None, '_socket_free': {<SSLSocket>: True}, '_open_sockets': {('io.adafruit.com', 443, 'https:'): <SSLSocket>}, '_socket_pool': <SocketPool>, '_ssl_context': <SSLContext>}
<SSLSocket>
call free socket
entering _free_sockets
entering _close_socket
retry_count: 2
trying to create sock
create https sock
try to connect with sock: httpbin.org:443
	_get_socket Session: {'_last_response': None, '_socket_free': {}, '_open_sockets': {}, '_socket_pool': <SocketPool>, '_ssl_context': <SSLContext>}
<SSLSocket>
no _socket_free.items()
	_get_socket Session: {'_last_response': None, '_socket_free': {}, '_open_sockets': {}, '_socket_pool': <SocketPool>, '_ssl_context': <SSLContext>}
Traceback (most recent call last):
  File "code.py", line 37, in <module>
  File "/lib/adafruit_requests.py", line 610, in get
  File "/lib/adafruit_requests.py", line 551, in request
  File "/lib/adafruit_requests.py", line 416, in _get_socket
RuntimeError: Sending request failed
```

**Comment by askpatrickw** [comment]
No, that's not right...
In the 2nd request, there is an "old" socket.
It frees and closes it. 
and it in the retry attempt its failing.

**Comment by askpatrickw** [comment]
I added a bunch of print statements and I see this pattern (which I don't understand).

When it works, before the `sock.connect((connect_host, port))`, self._socket_free is empty `'_socket_free': {}` and when it fails it has `'_socket_free': {<SSLSocket>: True}` when entering _get_socket.

Also, it never gets to more than the 2nd retry.

```
[tio 14:36:30] Connected
Wake Reason: None
entering Session __init__

# This works

946684814 Request 1
entering requests
entering _get_socket
key: ('io.adafruit.com', 443, 'https:')
_get_socket Session: {
    '_last_response': None, '_socket_free': {}, '_open_sockets': {}, 
    '_socket_pool': <SocketPool>, '_ssl_context': <SSLContext>}
retry_count: 1
set sock to Socket
	sock: <Socket>
set sock to SSL wrapped Socket
	sock: <SSLSocket>
try to connect with sock:<SSLSocket> io.adafruit.com:443
	_get_socket Session: {'_last_response': None, '_socket_free': {},
        '_open_sockets': {}, '_socket_pool': <SocketPool>,
        '_ssl_context': <SSLContext>}
entering _send_request
entering _send
entering _send
entering _send
entering _send
entering _send
entering _send
entering _send
entering _send
entering _send
entering _free_socket
System Time: struct_time(tm_year=2021, tm_mon=11, tm_mday=25, tm_hour=22,
    tm_min=36, tm_sec=42, tm_wday=3, tm_yday=329, tm_isdst=-1)

# This Fails

1637879806 Request 2
entering requests
entering _get_socket
key: ('httpbin.org', 443, 'https:')
_get_socket Session: {'_last_response': None,
    '_socket_free': {<SSLSocket>: True},
    '_open_sockets': {('io.adafruit.com', 443, 'https:'): <SSLSocket>},
    '_socket_pool': <SocketPool>, '_ssl_context': <SSLContext>}

# First attempt: We have an old sock for the last request

retry_count: 1
set sock to Socket
	sock: <Socket>
set sock to SSL wrapped Socket
	sock: <SSLSocket>
try to connect with sock:<SSLSocket> httpbin.org:443
	_get_socket Session: {'_last_response': None,
        '_socket_free': {<SSLSocket>: True},
        '_open_sockets': {('io.adafruit.com', 443, 'https:'): <SSLSocket>},
        '_socket_pool': <SocketPool>, '_ssl_context': <SSLContext>}

# Clean that up by freeing and closing.

call free socket
entering _free_sockets
entering _close_socket

# Try again

retry_count: 2
set sock to Socket
	sock: <Socket>
set sock to SSL wrapped Socket
	sock: <SSLSocket>
try to connect with sock:<SSLSocket> httpbin.org:443
	_get_socket Session: {'_last_response': None, '_socket_free': {},
        '_open_sockets': {}, '_socket_pool': <SocketPool>,
        '_ssl_context': <SSLContext>}

# I think `common_hal_socketpool_socket_connect` has failed in some way
# over in CP Core Land: common_hal_socketpool_socket_connect
# https://github.com/adafruit/circuitpython/blob/main/ports/espressif/common-hal/socketpool/Socket.c#L147

# But there is nothing to clean up so it bails.

no _socket_free.items()
	_get_socket Session: {'_last_response': None, '_socket_free': {},
        '_open_sockets': {}, '_socket_pool': <SocketPool>,
        '_ssl_context': <SSLContext>}
Traceback (most recent call last):
  File "code.py", line 39, in <module>
  File "/lib/adafruit_requests.py", line 612, in get
  File "/lib/adafruit_requests.py", line 553, in request
  File "/lib/adafruit_requests.py", line 417, in _get_socket
RuntimeError: Sending request failed
```

**Comment by askpatrickw** [comment]
It was failing almost every time on the 2nd request or sometime on the 2nd loop (after the timer). I tried replacing all the sites I was using and the test works way better, but it will eventually fail off in C-land and one time I had a hard fault. 👀

I'm running it some more with the latest released version, but so far much better with "better" endpoints.

```python
import alarm
import rtc
import socketpool
import ssl
import time
import wifi

import adafruit_requests

print(f"Wake Reason: {alarm.wake_alarm}")

# Get secrets
try:
    from secrets import secrets
except ImportError:
    print("Secrets are kept in secrets.py, please add them there!")
    raise

# Setup Requests
radio = wifi.radio
radio.connect(secrets['ssid'], secrets['wifi_password'])

pool = socketpool.SocketPool(radio)
requests = adafruit_requests.Session(pool, ssl.create_default_context())

print(f"\n{time.time()} Request 1")
# Use Adafruit Time API
# response = requests.get("https://io.adafruit.com/api/v2/time/seconds")
# if response:
#     if response.status_code == 200:
#         r = rtc.RTC()
#         r.datetime = time.localtime(int(response.text))
#         print(f"System Time: {r.datetime}")
#     else:
#         print("Setting time failed")

# Use Word Time API
response = requests.get("http://worldtimeapi.org/api/timezone/GMT")
print(response.status_code, response.reason)
if response:
    if response.status_code == 200:
        r = rtc.RTC()
        r.datetime = time.localtime(int(response.json()['unixtime']))
        print(f"System Time: {r.datetime}")
    else:
        print("Setting time failed")

print(f"\n{time.time()} Request 2")
response = requests.get("https://www.google.com/humans.txt")
print(response.status_code, response.reason)

print(f"\n{time.time()} Request 3")
response = requests.get("https://www.amazon.com/robots.txt")
print(response.status_code, response.reason)

print(f"\n{time.time()} Request 4")
response = requests.get("https://www.bing.com/robots.txt")
print(response.status_code, response.reason)

# Create a an alarm that will trigger requested number of seconds from now.
time_alarm = alarm.time.TimeAlarm(monotonic_time=time.monotonic() + 120)
# Exit and deep sleep until the alarm wakes us.
alarm.exit_and_deep_sleep_until_alarms(time_alarm)

```

**Comment by anecdata** [comment]
Are you using a CP version since <https://github.com/adafruit/circuitpython/pull/5562> that cured some hardfaults?

**Comment by anecdata** [comment]
I'm running the above code now with `Adafruit CircuitPython 7.1.0-beta.0 on 2021-11-12; Saola 1 w/Wrover with ESP32S2` (actually a DevKit-C but code-wise identical), with the addition of two of the links from the prior example (6 total, but not requestbin that's 404 for me). Should I be doing this in pretend deep sleep, or real deep sleep, or doesn't matter? Just a handful of loops so far, I'll update after it runs for a while or stops on its own.

**Comment by askpatrickw** [comment]
If I see the hard fault again, I'll try that. I only saw it once. 

I was running it with io.adafruit.com and httpbin.org back in the loop as the "better" endpoints were working very reliably and I'm wondering it there's a problem with the services. Because it does seem to fail more often.

```
Pretending to deep sleep until alarm, CTRL-C or file write.
Woken up by alarm.
soft reboot

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Wake Reason: <TimeAlarm>

1638140152 Request 1
System Time: struct_time(tm_year=2021, tm_mon=11, tm_mday=28, tm_hour=22, tm_min=55, tm_sec=55, tm_wday=6, tm_yday=332, tm_isdst=-1)

1638140155 Request 2
Traceback (most recent call last):
  File "code.py", line 49, in <module>
  File "/lib/adafruit_requests.py", line 603, in get
  File "/lib/adafruit_requests.py", line 544, in request
  File "/lib/adafruit_requests.py", line 439, in _get_socket
RuntimeError: Repeated socket failures

Code done running.
```

**Comment by anecdata** [comment]
I've been running those 6 URLs looping through pretend deep sleep for about 3-1/2 hours with no hiccups, but clearly some conditions are causing issues at times. Networking is bound to be error-prone, so long-running code will need to catch and handle exceptions in some way. But I think our goal is for the core and Requests to be as resilient and friendly as possible. If we can find patterns or predictability, that may be the best bet for fixes. I'll leave it going.

**Comment by askpatrickw** [comment]
I think we're seeing the same thing now. You get bonus points for using emoji in your print().
Ultimately I think the issue in the Core not in this library. 

I was looking at porting rety or tenacity, but they all require large swaths of Python libraries CP does not have and probably shouldn't have (too big).

If using requests should always involve a try, should we update all the samples to show that and document it?
The other issue is the recovery... website\networks are intermittently down or unavailable but having my project stop working because of that is not a great experience. We should offer advice about that.

**Comment by askpatrickw** [comment]
I also plan to run this in debug on my Kaluga, and see if I can gather more info on the CP part, I just have to make time to do that.

**Comment by MadMaxMcKinney** [comment]
Following this discussion as I'm facing what I think is a similar issue? Some education on this topic would be really helpful. I've got a MatrixPortal that I use to look at some Adafruit IO feeds (although I think I want to move to MQTT), and then based on their info the portal will change between "Free" and "Busy", pretty simple!

However after random amounts of time it will stop responding all together. The best error I was able to get from the serial in MU was
```
MatrixPortal "An error occurred 1 - repeated socket failures"

**Comment by kabcasa** [comment]
it seems that my case seems similar in the sense that I cannot manage for this url to retrieve the json response.
"http://calendar2.priyom.org/events?timeMin=2022-03-04T00:00:00.000Z&amp;timeMax=2022-03-05T00:00:00.000Z"
To check I took a common example.
The execution succeeds with the error:
File "adafruit_requests.py", line 563, in _get_socket
RuntimeError: Sending request failed

I had no problem getting the response with a requests on a python3 script.

>Currently my internet connection is a little weak and I suspect that this is the cause.
To confirm I would have liked someone with a better connection to do the test

`
# SPDX-FileCopyrightText: 2019 ladyada for Adafruit Industries
# SPDX-License-Identifier: MIT

import board
import busio
from digitalio import DigitalInOut
import adafruit_requests as requests
import adafruit_esp32spi.adafruit_esp32spi_socket as socket
from adafruit_esp32spi import adafruit_esp32spi

# Get wifi details and more from a secrets.py file
try:
    from secrets import secrets
except ImportError:
    print("WiFi secrets are kept in secrets.py, please add them there!")
    raise

print("ESP32 SPI webclient test")

TEXT_URL = "http://wifitest.adafruit.com/testwifi/index.html"
JSON_URL = "http://calendar2.priyom.org/events?timeMin=2022-03-04T00:00:00.000Z&amp;timeMax=2022-03-05T00:00:00.000Z"


# If you are using a board with pre-defined ESP32 Pins:
esp32_cs = DigitalInOut(board.ESP_CS)
esp32_ready = DigitalInOut(board.ESP_BUSY)
esp32_reset = DigitalInOut(board.ESP_RESET)


spi = busio.SPI(board.SCK, board.MOSI, board.MISO)
esp = adafruit_esp32spi.ESP_SPIcontrol(spi, esp32_cs, esp32_ready, esp32_reset)

requests.set_socket(socket, esp)

if esp.status == adafruit_esp32spi.WL_IDLE_STATUS:
    print("ESP32 found and in idle mode")
print("Firmware vers.", esp.firmware_version)
print("MAC addr:", [hex(i) for i in esp.MAC_address])

for ap in esp.scan_networks():
    print("\t%s\t\tRSSI: %d" % (str(ap["ssid"], "utf-8"), ap["rssi"]))

print("Connecting to AP...")
while not esp.is_connected:
    try:
        esp.connect_AP(secrets["ssid"], secrets["password"])
    except RuntimeError as e:
        print("could not connect to AP, retrying: ", e)
        continue
print("Connected to", str(esp.ssid, "utf-8"), "\tRSSI:", esp.rssi)
print("My IP address is", esp.pretty_ip(esp.ip_address))
print(
    "IP lookup adafruit.com: %s" % esp.pretty_ip(esp.get_host_by_name("adafruit.com"))
)
print("Ping google.com: %d ms" % esp.ping("google.com"))


# esp._debug = True
print("Fetching text from", TEXT_URL)
r = requests.get(TEXT_URL)
print("-" * 40)
print(r.text)
print("-" * 40)
r.close()

print()
print("Fetching json from", JSON_URL)
r = requests.get(JSON_URL)
print("-" * 40)
print(r.json())
print("-" * 40)
r.close()

print("Done!")
`
test result :

`
ESP32 SPI webclient test
ESP32 found and in idle mode
Firmware vers. bytearray(b'1.2.2\x00')
MAC addr: ['0xcc', '0x5f', '0x43', '0xc2', '0x9d', '0x1c']
Looney2 RSSI: -35
Looney5G RSSI: -48
Looney2 RSSI: -54
Looney2 RSSI: -55
Looney2 RSSI: -56
EasyLighting_23D26FB2 RSSI: -62
Looney2 RSSI: -67
Looney2 RSSI: -73
Looney2 RSSI: -77
Looney2 RSSI: -83
Connecting to AP...
Connected to Looney5G RSSI: -47
My IP address is ..................................
IP lookup adafruit.com: ..................
Ping google.com: 130 ms
Fetching text from http://wifitest.adafruit.com/testwifi/index.html
----------------------------------------
This is a test of Adafruit WiFi!
If you can read this, its working :)
----------------------------------------

Fetching json from http://calendar2.priyom.org/events?timeMin=2022-03-04T00:00:00.000Z&amp;timeMax=2022-03-05T00:00:00.000Z
Traceback (most recent call last):
File "code.py", line 68, in <module>
File "adafruit_requests.py", line 864, in get
File "adafruit_requests.py", line 758, in request
File "adafruit_requests.py", line 710, in request
File "adafruit_requests.py", line 563, in _get_socket
RuntimeError: Sending request failed

Code done running.
`

**Comment by anecdata** [comment]
@kabcasa Can you file a separate issue? This seems to be a different problem. The JSON file is 22k, I suspect that may have something to do with it. I doubt it's a signal strength issue. It fails for me also in the same way. If you only need some of the JSON, check out <https://docs.circuitpython.org/projects/portalbase/en/latest/api.html#module-adafruit_portalbase> and some examples of getting just some of the JSON, like <https://learn.adafruit.com/spacex-next-launch-display-with-adafruit-magtag/code>.

**Comment by kabcasa** [comment]
@anecdata 
Thank you for your comments.
Sorry but you said that it works with https but initially I had tested with https and it gives the same error for me that's why I tried with http.
I need this url because with the info obtained my project is to display on a 64x32 RGB LED Matrix.

**Comment by dsohrabian** [comment]
@anecdata Can you speak to your last comment a bit about 22k JSON file being an issue? Is there is a size limit for memory on the ESP chip or something to be aware of? Trying to debug a related issue to this case and not sure if I am just expecting the impossible hardware-wise or if it's a software bug.

**Comment by anecdata** [comment]
@dsohrabian That turned out to be an incorrect supposition. There probably are RAM (and other) limits on the size of a requested payload, but they would also depend on other loaded libraries, code, which MCU, etc.

**Comment by wavesailor** [comment]
I'm found another issue with the requests library call. Sample code from the "[MagTag Lists From Google Spreadsheets](https://learn.adafruit.com/collaborative-spreadsheets-to-magtag?view=all)" tutorial , should work but does not. Thought it may help to mention it here. I did log it under it's own [issue](https://github.com/adafruit/Adafruit_Learning_System_Guides/issues/2115):

It returns this error:
```
Connecting to AP MyWiFI
Updating time
Getting time for timezone America/New_York
Updating tasks
Retrieving data...Traceback (most recent call last):
  File "code.py", line 101, in <module>
  File "adafruit_portalbase/network.py", line 478, in fetch
  File "adafruit_requests.py", line 769, in get
  File "adafruit_requests.py", line 758, in request
  File "adafruit_requests.py", line 702, in request
  File "adafruit_requests.py", line 378, in close
ValueError: invalid syntax for integer with base 16

Code done running.
```

**Comment by scarolan** [comment]
I can confirm the same issue that @askpatrickw reported on a Qt Py ESP32-S3.

Moving the adafruit_requests.Session before the while loop fixed the issue for me.

**Comment by anecdata** [comment]
A variety of other behaviors have been raised in this discussion, but @askpatrickw: is the original issue still open?

**Comment by askpatrickw** [comment]
The original issue was cause by creating the `request` client (object) in the While loop.
Doing that before the while loop fixed it.

**Comment by gary-major** [comment]
Just posted an issue, which seems to be similar here -> https://github.com/adafruit/Adafruit_CircuitPython_AzureIoT/issues/44

my call to requests is outside of the white true loop.
