### ISSUE TITLE
using sockets as dict keys

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_Requests#66]
`.socket_free` is a dict that uses a socket as a key. To enable this, `__hash__()` was added to the native `Socket` class. However, the hash value used is not immutable: https://github.com/adafruit/circuitpython/issues/4101.

The hash function could be fixed, or perhaps the use of a dict that needs to use sockets as a key could be revisited here.

Encountered while debugging https://github.com/adafruit/circuitpython/issues/4061 with @hierophect.

**Comment by tannewt** [comment]
I think the socket fix is the correct one. Sockets should work as keys.

**Comment by dhalbert** [comment]
Fixed by https://github.com/adafruit/circuitpython/pull/4049.
