### ISSUE TITLE
SSL handshake failures are not caught

### ISSUE THREAD

**Issue by hierophect** [adafruit/Adafruit_CircuitPython_Requests#67]
[In the request method](https://github.com/adafruit/Adafruit_CircuitPython_Requests/blob/f658b39ff84231b0be8e827fd676073e195a266c/adafruit_requests.py#L563), while attempting to send a request, only `_SendFailed` exceptions are caught and all others (such as a `Failed SSL handshake`, which may occur after too much time has elapsed between requests) are ignored. This then leads to `recv` or `recv_into` being run on an invalid connection, resulting in an exception and potentially a socket leak.

This was discovered while debugging adafruit/circuitpython#4061, but does not wholly fix the issue as the code will then run into issue #66. May be related to #63.

**Comment by hierophect** [comment]
I fixed this for my example program by simply replacing `except _sendFailed:` with `except:` but I don't know if there's issues with that?

**Comment by tannewt** [comment]
Ya, don't do `except:` because you'll catch absolutely everything. You can add a second except for the error type of "Failed SSL handshake" though.

**Comment by hierophect** [comment]
@tannewt what's the issue with catching everything here? Is there an exception that's considered acceptable? All the step does is mark that the socket is not ready to receive data and close it, which seems like the right thing to do for any exception.

**Comment by hierophect** [comment]
Alternatively I could add in an `else:` to actually raise exceptions that aren't of the two specified types.

**Comment by tannewt** [comment]
> @tannewt what's the issue with catching everything here? Is there an exception that's considered acceptable? All the step does is mark that the socket is not ready to receive data and close it, which seems like the right thing to do for any exception.

Catching everything is bad because you'll catch extra stuff. Reload, keyboard and deep sleep all use exceptions. Those things (or others) may be caught higher and the code will expect the socket to continue. So, *always* be explicit with catching exceptions.

**Comment by anecdata** [comment]
Closed by #70
