### ISSUE TITLE
Lack of "params" keyword in request() and related methods

### ISSUE THREAD

**Issue by tekktrik** [adafruit/Adafruit_CircuitPython_Requests#88]
It looks like `request` and related functions don't take a `param` keyword like their CPython equivalents.  However, passing the query parameters as part of the URL does work, so it's not missing that functionality, just how it's achieved.  Is there a reason for that?

**Comment by tannewt** [comment]
I don't think so. We just didn't implement it.

**Comment by tekktrik** [comment]
If it works without it, is it a change worth making?  I could add a PR that just basically takes any params and adds it to the URL so it should be backward compatible.  I think the only thing I'd have to make sure of is that I'm quoting and escaping characters appropriately.

**Comment by tannewt** [comment]
I wouldn't add it because it'll increase the library size.

This is where the "CircuitPython APIs are a subset of CPython APIs" is important. CircuitPython code should work in CPython but not necessarily the other way around. CPython's API is very broad and we simply can't implement it all.

**Comment by tekktrik** [comment]
Makes sense, sounds good!  Closing because the functionality exists then.
