### ISSUE TITLE
Module 'types' not found in CircuitPython 7.1.0

### ISSUE THREAD

**Issue by wellsta103** [adafruit/Adafruit_CircuitPython_Requests#92]
adafruit_requests.py, version 1.10.3+ imports module 'types' which is not defined in CircuitPython 7.1.0:

ImportError: no module named 'types'

**Comment by dhalbert** [comment]
This is fixed by https://github.com/adafruit/Adafruit_CircuitPython_Requests/releases/tag/1.10.4, which will be in the bundle tonight.

**Comment by FoamyGuy** [comment]
Confirmed with pyportal and install from today's bundle this is resolved.

**Comment by ladyada** [comment]
thankya!
